name: pm-automation
on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [opened, edited, ready_for_review]

jobs:
  label-and-project:
    runs-on: ubuntu-latest
    steps:
      - name: Auto label by title keywords
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: >
            ${{ contains(github.event.issue.title, 'refactor') && 'refactor' || '' }},
            ${{ contains(github.event.issue.title, 'test') && 'test' || '' }},
            ${{ contains(github.event.issue.title, 'feature') && 'feature' || '' }}

      - name: Add to project board
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
